title: Mehmet Fatih Okuyan
description: Personal Blog
author: Mehmet Fatih Okuyan
logo: /static/img/avatar.png
github: https://github.com/okuyanf61
about: Computer engineering student. Always hungry to keep learning.

baseurl: "/"
url: ""

allowsearch: true

disqus_shortname: mehmetfatih
google_analytics: UA-63123983-3

share:
  twitter_username: \#
  fb_appid: 000000000000

enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
